CREATE TABLE ROL(
Id_Rol INT AUTO_INCREMENT NOT NULL,
Nombre_Rol VARCHAR(50) NOT NULL,
PRIMARY KEY (Id_Rol)
);

CREATE TABLE CIUDAD(
Id_Ciudad INT AUTO_INCREMENT NOT NULL,
Nombre_Ciudad VARCHAR(50) NOT NULL,
Cuantia FLOAT NOT NULL,
PRIMARY KEY (Id_Ciudad)
);

CREATE TABLE CENTRO(
Id_Centro INT AUTO_INCREMENT NOT NULL,
Nombre VARCHAR(50) NOT NULL,
Cuantia FLOAT NOT NULL,
Id_Ciudad INT NOT NULL,
PRIMARY KEY (Id_Centro), 
FOREIGN KEY (Id_Ciudad) REFERENCES CIUDAD(Id_Ciudad)
);

CREATE TABLE TIPO_MOVIMIENTO(
Id_TipoMov INT AUTO_INCREMENT NOT NULL,
Nombre_TipoMov VARCHAR(50) NOT NULL,
PRIMARY KEY (Id_TipoMov)
);

CREATE TABLE ESPECIALIDAD(
Id_Especialidad INT AUTO_INCREMENT NOT NULL,
Nombre VARCHAR(50) NOT NULL,
PRIMARY KEY (Id_Especialidad)
);

CREATE TABLE MATERIAL(
Id_Material INT AUTO_INCREMENT NOT NULL, 
Nombre VARCHAR(50) NOT NULL,
Archivo VARCHAR(100) NOT NULL,
PRIMARY KEY (Id_Material)
);




CREATE TABLE PERSONA (
Id_Persona INT AUTO_INCREMENT NOT NULL,
Nombre VARCHAR(50) NOT NULL,
Apellidos VARCHAR(50) NOT NULL,
Direccion VARCHAR(80) NOT NULL,
Fecha_Nacimiento DATE NOT NULL,
Telefono VARCHAR(15),
Email VARCHAR(50),
Nom_User VARCHAR(30),
Password VARCHAR(20),
Id_Rol INT,

PRIMARY KEY (Id_Persona),
FOREIGN KEY (Id_Rol) REFERENCES ROL(Id_Rol)
);


CREATE TABLE PROFESOR(
Id_Persona INT AUTO_INCREMENT NOT NULL,
PRIMARY KEY (Id_Persona),
FOREIGN KEY (Id_Persona) REFERENCES PERSONA(Id_Persona)
);

CREATE TABLE TRABAJADOR(
Id_Persona INT AUTO_INCREMENT NOT NULL,
PRIMARY KEY (Id_Persona),
FOREIGN KEY (Id_Persona) REFERENCES PERSONA(Id_Persona)
);

CREATE TABLE ALUMNO(
Id_Persona INT AUTO_INCREMENT NOT NULL,
Curso_Actual VARCHAR(20) NOT NULL,
Tutor_Legal VARCHAR(50) NOT NULL,
PRIMARY KEY (Id_Persona),
FOREIGN KEY (Id_Persona) REFERENCES PERSONA(Id_Persona)
);

CREATE TABLE BECA(
Id_Beca INT AUTO_INCREMENT NOT NULL,
Importe VARCHAR(20) NOT NULL,
Observaciones VARCHAR(150),
Fecha_Beca DATE NOT NULL,
Nota_Media FLOAT NOT NULL,
Id_Persona INT NOT NULL,
Id_Centro INT NOT NULL,
PRIMARY KEY (Id_Beca),
FOREIGN KEY (Id_Persona) REFERENCES ALUMNO(Id_Persona),
FOREIGN KEY (Id_Centro) REFERENCES CENTRO(Id_Centro)
);

CREATE TABLE JRM(
Id_Beca INT AUTO_INCREMENT NOT NULL,
PRIMARY KEY (Id_Beca),
FOREIGN KEY (Id_Beca) REFERENCES BECA(Id_Beca)
);

CREATE TABLE REFUGIO(
Id_Beca INT AUTO_INCREMENT NOT NULL,
PRIMARY KEY (Id_Beca),
FOREIGN KEY (Id_Beca) REFERENCES BECA(Id_Beca)
);

CREATE TABLE CARRERA(
Id_Beca INT AUTO_INCREMENT NOT NULL,
PRIMARY KEY (Id_Beca),
FOREIGN KEY (Id_Beca) REFERENCES BECA(Id_Beca)
);

CREATE TABLE MADRINA(
Id_Persona INT AUTO_INCREMENT NOT NULL,
Id_Beca INT NOT NULL,
Fecha_Financiacion DATE NOT NULL,
PRIMARY KEY (Id_Persona),
FOREIGN KEY (Id_Persona) REFERENCES PERSONA(Id_Persona),
FOREIGN KEY (Id_Beca) REFERENCES CARRERA(Id_Beca)
);



CREATE TABLE MOVIMIENTO(
Id_Movimiento INT AUTO_INCREMENT NOT NULL,
Fecha DATE NOT NULL,
Procedencia VARCHAR(50) NOT NULL,
Accion VARCHAR(20) NOT NULL,
Id_TipoMov INT NOT NULL,
Id_Beca INT,
PRIMARY KEY (Id_Movimiento),
FOREIGN KEY (Id_TipoMov) REFERENCES TIPO_MOVIMIENTO(Id_TipoMov),
FOREIGN KEY (Id_Beca) REFERENCES BECA(Id_Beca)
);

CREATE TABLE TIPO_PRESTAMO(
Id_TipoPrestamo INT AUTO_INCREMENT NOT NULL,
Nombre VARCHAR(50),
PRIMARY KEY (Id_TipoPrestamo)
);

CREATE TABLE PRESTAMO(
Id_Prestamo INT AUTO_INCREMENT NOT NULL,
Concepto VARCHAR(50) NOT NULL,
Importe FLOAT NOT NULL,
Estado VARCHAR(30) NOT NULL,
Observaciones VARCHAR(150),
Fecha_Fin DATE,
Fecha_Inicio DATE NOT NULL,
Id_Persona INT NOT NULL,
Id_TipoPrestamo INT NOT NULL,
Id_Movimiento INT NOT NULL,
PRIMARY KEY (Id_Prestamo),
FOREIGN KEY (Id_Persona) REFERENCES PERSONA(Id_Persona),
FOREIGN KEY (Id_TipoPrestamo) REFERENCES TIPO_PRESTAMO(Id_TipoPrestamo),
FOREIGN KEY (Id_Movimiento) REFERENCES MOVIMIENTO(Id_Movimiento)
);

CREATE TABLE ABONO(
Id_Abono INT AUTO_INCREMENT NOT NULL,
Id_Prestamo INT NOT NULL,
Fecha DATE NOT NULL,
Cantidad FLOAT NOT NULL,
Id_Movimiento INT NOT NULL,
PRIMARY KEY (Id_Abono),
FOREIGN KEY (Id_Prestamo) REFERENCES PRESTAMO(Id_Prestamo),
FOREIGN KEY (Id_Movimiento) REFERENCES MOVIMIENTO(Id_Movimiento)
);


CREATE TABLE CURSO(
Id_Curso INT AUTO_INCREMENT NOT NULL,
Nombre VARCHAR(50) NOT NULL,
Importe FLOAT  NOT NULL,
Fecha_Impartir DATE NOT NULL,
Id_Persona INT NOT NULL,
Id_Especialidad INT NOT NULL,
Id_Movimiento INT NOT NULL,
PRIMARY KEY(Id_Curso),
FOREIGN KEY (Id_Persona) REFERENCES PROFESOR(Id_Persona),
FOREIGN KEY (Id_Especialidad) REFERENCES ESPECIALIDAD(Id_Especialidad),
FOREIGN KEY (Id_Movimiento) REFERENCES MOVIMIENTO(Id_Movimiento)
);

CREATE TABLE ESPECIALIZAR(
Id_Especialidad INT NOT NULL,
Id_Persona INT NOT NULL,
PRIMARY KEY(Id_Especialidad, Id_Persona),
FOREIGN KEY (Id_Especialidad) REFERENCES ESPECIALIDAD(Id_Especialidad),
FOREIGN KEY (Id_Persona) REFERENCES TRABAJADOR(Id_Persona)
);

CREATE TABLE RECIBIR(
Id_Curso INT NOT NULL,
Id_Persona INT NOT NULL,
Fecha DATE NOT NULL,
PRIMARY KEY(Id_Curso, Id_Persona),
FOREIGN KEY (Id_Curso) REFERENCES CURSO(Id_Curso),
FOREIGN KEY (Id_Persona) REFERENCES TRABAJADOR(Id_Persona)
);

CREATE TABLE POSEER(
Id_Material INT NOT NULL,
Id_Curso INT NOT NULL,
PRIMARY KEY(Id_Curso, Id_Material),
FOREIGN KEY (Id_Curso) REFERENCES CURSO(Id_Curso),
FOREIGN KEY (Id_Material) REFERENCES MATERIAL(Id_Material)
);





